drop table if exists books;

create table books (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    author varchar(100) not null,
    isbn varchar(20) not null,
    publish_date date not null,
    price integer not null
);

create unique index uk_books_isbn on books(isbn);